#!/usr/bin/env bash
# Create the Key Vault secrets the api needs, if they don't exist yet.
#
#   scripts/azure/bootstrap-secrets.sh <staging|production>
#
# Secret values are never Bicep parameters or files in git. This generates them
# on your machine and writes them straight to Key Vault. Existing secrets are
# left alone, so it is safe to re-run. Requires the "Key Vault Secrets Officer"
# role that main.bicep grants to VAULT_ADMIN_PRINCIPAL_ID (you, by default).
#
#   secret-key   JWT signing key (backend SECRET_KEY), 32 random bytes as hex

source "$(dirname "$0")/lib.sh"

[[ $# -eq 1 ]] || die "usage: $0 <staging|production>"
rentflow_env "$1"
command -v openssl >/dev/null || die "openssl is required to generate secrets"

ensure_secret() {
  local name=$1 generator=$2 attempt
  # A fresh role assignment can take a few minutes to apply; retry reads too.
  for attempt in $(seq 1 18); do
    if az keyvault secret show --vault-name "$KEY_VAULT" --name "$name" --query id -o tsv >/dev/null 2>&1; then
      log "$name already exists in $KEY_VAULT; leaving it"
      return 0
    fi
    if value=$($generator) && az keyvault secret set --vault-name "$KEY_VAULT" --name "$name" \
      --value "$value" --content-type "generated by bootstrap-secrets.sh" -o none 2>/dev/null; then
      log "created $name in $KEY_VAULT"
      return 0
    fi
    warn "Key Vault not writable yet (role assignment propagating?); retry $attempt/18"
    sleep 10
  done
  die "could not create $name in $KEY_VAULT"
}

jwt_key() { openssl rand -hex 32; }

ensure_secret secret-key jwt_key
# azure-communication-connection-string is added in M7 (notifications).
